**TASKS**

In [1]:
import numpy as np

**1)array creation**

In [2]:
#create 1d array of numbers from 10 to 40

arr=np.arange(10,41)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [3]:
#create a 2x2 array of random numbers between 0 and 1

rarr=np.random.rand(2, 2)
rarr

array([[0.04004807, 0.74868645],
       [0.62496605, 0.02212615]])

**2)Array Attributes**

In [4]:
#Find the shape size and datatype of the array you created in previous task

print("shape:",np.shape(rarr))
print("size:",np.size(rarr))
print("datatype:",rarr.dtype)

shape: (2, 2)
size: 4
datatype: float64


**3)Basic Operations**

In [5]:
#Add 5 to every element of 1d array

a=[1,2,3,4,5]
b=np.add(a,10)
b

array([11, 12, 13, 14, 15])

In [6]:
#Multipy 2 2d arrays element wise 

arr1 = np.random.rand(3, 3)
arr1


array([[0.80702937, 0.47784623, 0.72397422],
       [0.97370464, 0.18967808, 0.77109637],
       [0.62092226, 0.92229672, 0.25206236]])

In [7]:
arr2 = np.random.rand(3, 3)
arr2

array([[0.30844601, 0.97721861, 0.7005567 ],
       [0.17078277, 0.42686269, 0.28565275],
       [0.41317629, 0.49621222, 0.17330187]])

In [8]:
mul=np.dot(arr1,arr2)
mul

array([[0.62966187, 1.3518637 , 0.82733401],
       [0.6513278 , 1.41511623, 0.86994982],
       [0.45317957, 1.12554727, 0.74213072]])

**4)Indexing and slicing**

In [9]:
#create a 5x5 array of integers from 1 to 25 .extract: 
#.The first row 
#.the last column 
#.a subarray of the first 3 rows and first 2 columns
arr = np.arange(1, 26).reshape(5, 5)
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [10]:
#.The first row 
arr[0, :]

array([1, 2, 3, 4, 5])

In [11]:
#.the last column
arr[:,-1]

array([ 5, 10, 15, 20, 25])

In [12]:
#.a subarray of the first 3 rows and first 2 columns
arr[:3, :2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

**5)Aggregation**

In [13]:
#create 10-element array of random integers between 1 to 100.find:
#the max value
#the min value
#the mean and std

random_ints = np.random.randint(1, 101, size=10)
random_ints


array([20, 60, 46, 72, 93, 94, 27, 69, 95, 21])

In [14]:
#the max value

np.max(random_ints)

95

In [15]:
#the min value

np.min(random_ints)

20

In [16]:
#the mean 

np.mean(random_ints)


59.7

In [17]:
#std

np.std(random_ints)

28.46067462306542

**6)Reshaping**

In [18]:
#convert a 1d array of numbers from 1 to 12 into 3x4 matrix

arr_3=np.arange(1,13)
arr_3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
reshaped_arr = arr_3.reshape(3, 4)
reshaped_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**7)Broadcasting**

In [20]:
#create a 3x3 martrix of ones.add a 1d array[1,2,3] to eac row 

ones=np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
e=[1,2,3]
f=np.add(ones,e)
f

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

**8)Filtering**

In [22]:
#create a 1D array of random integers between 1 and 50 .
#extract all elements that are divisible by 5

rand_a=np.arange(1,50)
rand_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [23]:
for i in rand_a :
    if i%5==0:
        print(i)

5
10
15
20
25
30
35
40
45


**9)Matrix multiplication**

In [24]:
#create 2 2x2 martices and perform matrix multiplication

var1 = np.random.rand(2, 2)
var1

array([[0.61099393, 0.21262143],
       [0.54715472, 0.61828991]])

In [25]:
var2=np.random.rand(2,2)
var2

array([[0.87496224, 0.59021752],
       [0.27061318, 0.42307712]])

In [26]:
var3=np.dot(var1,var2)
var3

array([[0.59213478, 0.45057459],
       [0.64605712, 0.58452462]])

**10)Advanced Indexing**

In [27]:
#given a 4x4 matrix ,use fancy indexing to extract the diagonal elements

mat= np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12],
               [13, 14, 15, 16]])

mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [28]:
dia_eles = mat[np.arange(4), np.arange(4)]
dia_eles

array([ 1,  6, 11, 16])

In [29]:
np.diagonal(mat)

array([ 1,  6, 11, 16])